services:
  snell-panel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snell-panel
    restart: always
    ports:
      - "9997:8080"
    environment:
      - API_TOKEN=1234567890
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
    volumes:
      - ./data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge