name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up CGO dependencies
      run: |
        if [ "${{ matrix.goos }}" = "linux" ]; then
          sudo apt-get update && sudo apt-get install -y gcc-multilib
        elif [ "${{ matrix.goos }}" = "windows" ]; then
          sudo apt-get update && sudo apt-get install -y gcc-mingw-w64
        elif [ "${{ matrix.goos }}" = "darwin" ]; then
          brew install FiloSottile/musl-cross/musl-cross
        fi

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1
      run: |
        if [ "${{ matrix.goos }}" = "windows" ]; then
          export CC=x86_64-w64-mingw32-gcc
        elif [ "${{ matrix.goos }}" = "darwin" ]; then
          export CC=o64-clang
        fi
        go build -v -o snell-panel-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: snell-panel-${{ matrix.goos }}-${{ matrix.goarch }}
        path: snell-panel-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./snell-panel-${{ matrix.goos }}-${{ matrix.goarch }}